# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

## our site wide variables
latest: 4.9.10

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Subsurface
author: "The Subsurface Developers"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://subsurface.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SubsurfaceDive
github_username:  Subsurface

# Build settings
theme: minima
encoding: UTF-8
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

lang: en 
languages:
  - short: "en"
    long: "English"
    base: ""
    flag: "ðŸ‡ºðŸ‡¸"
    userForum: "user forum"
  - short: "de"
    long: "Deutsch"
    base: "/de"
    flag: "ðŸ‡©ðŸ‡ª"
    userForum: "Benutzer-Forum"
  - short: "nl"
    long: "Nederlands"
    base: "/nl"
    flag: "ðŸ‡³ðŸ‡±"
    userForum: "user forum"
  - short: "es"
    long: "EspaÃ±ol"
    base: "/es"
    flag: "ðŸ‡ªðŸ‡¸"
    userForum: "user forum"
  - short: "pt"
    long: "PortuguÃªs"
    base: "/pt"
    flag: "ðŸ‡µðŸ‡¹"
    userForum: "user forum"

permalink: /:categories/:year/:month/:title/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
